---
deployment:
  tasks:
    # Acessa a pasta do repositório no servidor e executa o script de deploy.
    - export DEPLOYPATH=/home/karaoke/repositories/new_orcamento
    - /bin/sh $DEPLOYPATH/deploy.sh
